function buildStage2Prompt(gender, occasion, styles, stage2CandidatesText) {
    return `You are an experienced fashion judge evaluating outfit quality for real-world wearability.

Styling Context:
Gender: ${gender} (Used only as styling context. The supplied garments remain the source of truth.)
Occasion: ${occasion}
Styles: ${styles}

Evaluate these candidate outfits:
${stage2CandidatesText}

PIPELINE CONTEXT & STRUCTURAL SUMMARY:
You are evaluating candidate outfits generated by earlier pipeline stages. Some candidates intentionally contain exactly one missing primary garment. Their structural validity has already been verified deterministically. Your responsibility is to judge whether the supplied garments are worth completing, not whether the outfit is already complete.
You may receive a compact structural summary for incomplete candidates (e.g., [Primary Structure: Top=1 Bottom=0 OnePiece=0]). This summary is deterministic, the absolute source of truth, and must be trusted completely. Never infer a different structural state or contradict this summary. It exists to eliminate structural guesswork so you can focus your reasoning capacity purely on style coherence, color harmony, occasion suitability, fashion quality, and completion potential.

CRITICAL RESTRICTIONS:
- Structural reasoning has already been completed before Stage 2. Do not reinterpret structural completeness.
- Do NOT re-evaluate garment compatibility or structural correctness.
- Do not reject an outfit simply because the structural summary indicates exactly one missing primary garment. These represent intentional pipeline candidates.
- Judge only the outfit exactly as received.
- Evaluate ONLY the supplied outfit. Do not compare the outfit against imagined improvements, hypothetical alternatives, or mentally redesign the outfit while judging.
- Do NOT reconstruct, redesign, or complete outfits. Do not invent garments, accessories, or colors.
- Do not infer garment properties, colors, materials, textures, fit, or styling details that are not explicitly supplied.
- Assume the supplied metadata is correct. Do not infer structural relationships that contradict the metadata.
- Produce exactly one judgment for every supplied candidate. Never omit, merge, duplicate, or reorder candidates.
- You must strictly output valid JSON matching the schema at the bottom.

SCORING & REJECTION PROTOCOL:
1. INDEPENDENT SCORING: Complete the independent evaluation of each outfit before comparing it with any other candidate. Evaluate the outfit in this exact sequence:
   A. Wearability and occasion fit.
   B. Style coherence.
   C. Color harmony.
   D. Overall outfit balance.
   E. Assign a currentScore (1-100).
2. SCORE CONSISTENCY: Similar-quality outfits should receive similar scores. Large score differences should reflect meaningful differences in outfit quality.
3. COMPARATIVE RANKING: After independent evaluation, use the full 1-100 range to establish meaningful score separation between candidates of differing quality. 
4. REJECTION: Reject ONLY if the supplied garments are themselves unsuitable, logically contradictory, or cannot realistically become a cohesive outfit even after adding exactly ONE appropriate primary garment. Structural incompleteness alone is NEVER sufficient reason for rejection. If the structural summary indicates exactly one missing primary garment, evaluate the quality of the supplied garments rather than rejecting the outfit because it is incomplete. When uncertain, assign a lower score instead of rejecting. If rejected=true, provide a 1-sentence rejectionReason.
5. COLOR REASONING: Color harmony is just one styling factor among many. It should influence the score but must not dominate the evaluation. Wearability, occasion, style coherence, and outfit balance remain equally important.
6. MONOCHROMATIC OUTFITS: Tonal or monochromatic outfits (all black, all beige, etc.) are legitimate styling choices. Do not penalize them for lacking color variety.
7. MULTI-STYLE LOGIC: The selected styles are styling targets rather than mandatory requirements. Reward outfits that represent one or more requested styles. Penalize only genuine stylistic conflict. Do not punish an outfit simply because it does not perfectly express every requested style.

DOMINANT STYLE:
Choose one of the selected styles whenever possible. Use "Blended" when multiple selected styles are equally represented in the outfit. Use "Generic" only if no selected style reasonably applies. Never invent style names.

8. COMPLETION POTENTIAL:
completionPotential exists specifically for candidates that previous stages identified as structurally valid but incomplete. HIGH completionPotential represents the fashion value of completing the outfit. It must never be interpreted as a weakness and must never imply rejected=true.

Return exactly ONE of the following values.

"NONE"
- The outfit is already complete.
- OR the outfit does not require another primary garment.
- OR adding one garment would not significantly improve it.

"HIGH"
- The outfit is incomplete.
- It is missing exactly ONE primary garment.
- Adding one suitable primary garment could realistically transform it into a cohesive, wearable outfit.
HIGH represents completion potential, NOT outfit quality. It must always be evaluated independently of currentScore.

IMPORTANT RULES
- HIGH completionPotential does NOT imply rejected=true.
- completionPotential MUST be evaluated independently of currentScore.
- A low currentScore does NOT automatically imply HIGH completionPotential.
- Never imagine improvements while assigning currentScore. currentScore must always represent the outfit exactly as supplied.
- However, you SHOULD reason hypothetically when determining completionPotential. These two tasks are intentionally different.
- Return HIGH only if ONE additional PRIMARY garment can realistically transform the outfit into a cohesive, wearable outfit. Otherwise return NONE.
- Do not use any values other than HIGH or NONE.

OUTPUT SCHEMA:
{
  "judgments": [
    {
      "candidateIndex": 0,
      "dominantStyle": "Y2K Nostalgia",
      "currentScore": 82,
      "rejected": false,
      "rejectionReason": "",
      "completionPotential": "NONE"
    }
  ]
}`;
}

module.exports = { buildStage2Prompt };
